#!/bin/sh

# place the commands to run after the pppd dial up successfully.

if [ -x /bin/qos_run ]; then
	echo "/bin/qos_run"
	/bin/qos_run
fi

if [ -x /sbin/ddns.sh ]; then
	echo "/sbin/ddns.sh"
	/sbin/ddns.sh
fi

if [ -x /sbin/config-udhcpd.sh ]; then
	echo "/sbin/config-udhcpd.sh $DNS1 $DNS2"
	/sbin/config-udhcpd.sh -d $DNS1 $DNS2
fi

nvram set WanCurrentIP=$4
led 43 on
/usr/shell/ntp.sh start &
#echo "1.$1" ppp0
#echo "2.$2" /dev/ttyUSB0
#echo "3.$3" 9600
#echo "4.$4" wanip
#echo "5.$5" gateway
#echo "DNS1.$DNS1" DNS1
#echo "DNS2.$DNS2" DNS2

# notify goahead that WAN IP has been acquired/updated.
killall -SIGTSTP goahead
