/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Name of package */
#define PACKAGE "psntp"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "fuyuki@hadaly.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "psntp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "psntp 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "psntp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Version number of package */
#define VERSION "0.1"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
