{"cfg_management_log_event.htm", -1},
{"cfg_raid_modify.htm",0},
{"cfg_management_log_hardware.htm",-1},
{"cfg_raid_status.htm",-1},
{"index.htm", 1},
{"cfg_management_log_nvr.htm",-1},
{"cfg_recording_contactors.htm",0},
{"BCNVR.cab", 1},
{"cfg_management_saveConfig.htm",-1},
{"cfg_recording_email_contactors.htm",0},
{"FirmwareUpgrade.htm",0},
{"cfg_management_user_create.htm",-1},
{"cfg_recording_email_smtp.htm",0},
{"logout.htm",0},
{"cfg_camera_parameter.htm",0},
{"cfg_management_user_modify.htm",-1},
{"cfg_recording_mode.htm", 0},
{"upnp_waiting_page.htm",0},
{"cfg_camera_search.htm",0},
{"cfg_management_user_passwd.htm",0},
{"cfg_recording_schedule.htm",0},
{"waiting_page.htm",0},
{"cfg_camera_search_complete.htm",0},
{"cfg_network_cms.htm",0},
{"cfg_recording_schedule_cfg.htm",0},
{"waiting_page_loadConfig.htm",0},
{"cfg_camera_search_complete_1.htm",0},
{"cfg_network_info.htm",0},
{"cfg_system_buzzer.htm",-1},    
{"waiting_page_reboot.htm",0},
{"cfg_camera_search_complete_2.htm",0},
{"cfg_network_jumbo.htm",0},
{"cfg_system_enclosure_info.htm",0},
{"waiting_page_saveConfig.htm",0},
{"cfg_camera_settings.htm",0},
{"cfg_network_playback.htm",0},
{"cfg_system_info.htm",0},
{"waiting_page_shutdown.htm",0},
{"cfg_camera_status.htm",0}, 
{"cfg_network_port.htm",0},
{"cfg_system_reboot_shutdown.htm",-1},
{"waiting_page_upgrade.htm",0},
{"cfg_event_action.htm",0},
{"cfg_network_setup.htm",0},
{"cfg_system_setup.htm",-1},
{"waiting_page_upnp.htm",0},
{"cfg_event_email.htm",0},
{"cfg_playback_list.htm", 1},
{"cfg_system_time.htm",0},
{"waiting_page_user_create.htm",0},
{"cfg_event_enabled.htm",0},
{"cfg_playback_list_clear.htm", 1},
{"cfg_system_upgrade.htm",-1},
{"waiting_page_user_modify.htm",0},
{"cfg_filesystem_management.htm",-1},
{"cfg_playback_searchList.htm", 1},
{"cfg_system_upgradeError1.htm",0},
{"waiting_page_user_passwd.htm",0},
{"cfg_live_view.htm", 1},
{"cfg_protocol_ftp.htm",0},
{"cfg_system_upgradeError2.htm",0},
{"working.htm",0},
{"cfg_liveview_list.htm", 1},
{"cfg_protocol_info.htm",-1},
{"yui",0},
{"cfg_management_loadConfig.htm", 0},
{"cfg_protocol_windows.htm",0},
{"help_camera.htm",0},
{"cfg_management_loadConfigError1.htm",0},
{"cfg_raid_create.htm",0},
{"hw_test.htm",0},
{"cfg_management_loadConfigError2.htm",0},
{"cfg_raid_delete.htm",0},
{"cfg_management_guest_passwd.htm", 1},
{"cfg_camera_auto_detection.htm", 1},
{"cfg_recording_email_smtp_test.htm", 0},
{"cfg_playback_select_ipcamera.htm", 1},
